import {useEffect,useState} from 'react'
import {vibeClient} from '../lib/vibe'
export type Assessment={decision:string;reason:string;evidence:string;contribution:string;version:number|string;manual?:boolean}
type Rules={general:string;relevance:string;summary:string;metadata:string;image:string;sources:Record<string,string>}
type State={active:number;revision:number;draft:Rules;history:{version:number;created:string;rules:Rules}[];sources:{id:string;name:string}[];assessments:Record<string,Assessment>}
export async function rulesRequest(body?:unknown){const client=await vibeClient();const response=await client.authorizedFetch(new URL('/api/editor/rules',location.origin),await client.connect('app:content'),body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(210000)}:{});const result=await response.json();if(!response.ok)throw new Error(result.error||'Kunde inte läsa AI-regler.');return result}
const labels={general:'Gemensamma grundregler',relevance:'Relevansbedömning',summary:'Sammanfattning',metadata:'Kategori och sätt att bidra',image:'Bildinstruktioner'}
export const decisionLabel=(value:string)=>({recommended:'Rekommenderad',uncertain:'Osäker',rejected:'Bortsorterad av AI'}[value]||'Ej bedömd')
export default function AIRules({candidates,onAssessments}:{candidates:{entityId:string;payload:{title:string;state:string}}[];onAssessments:(items:Record<string,Assessment>)=>void}){
 const [state,setState]=useState<State>(),[draft,setDraft]=useState<Rules>(),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[results,setResults]=useState<(Assessment&{id:string;title:string;summary?:string;imagePrompt?:string;skipped?:boolean})[]>([])
 async function load(){const data=await rulesRequest();setState(data);setDraft(data.draft);onAssessments(data.assessments)}
 useEffect(()=>{void load().catch(error=>setMessage(error.message))},[])
 async function run(action:string){if(!state||!draft)return;setBusy(true);setMessage('');try{const data=await rulesRequest({action,rules:draft,revision:state.revision,ids:selected});if(data.results){setResults(data.results);onAssessments((await rulesRequest()).assessments);setMessage(action==='test'?'Test klart. Inga bedömningar eller initiativ ändrades.':'Valda förslag har omprövats. Manuella beslut bevaras.')}else{setState(data);setDraft(data.draft);onAssessments(data.assessments);setMessage(action==='activate'?`Version ${data.active} är aktiv för kommande bearbetning.`:'Utkast sparat. Aktiva regler är oförändrade.')}}catch(error){setMessage(error instanceof Error?error.message:'Kunde inte spara.')}finally{setBusy(false)}}
 return <details className="ai-rules"><summary>AI-regler {state&&`· aktiv version ${state.active}`}</summary><p>Testa på högst tre valda förslag innan du aktiverar. Testerna använder appens textanrop men skapar inga bilder och publicerar ingenting.</p>
 {message&&<p role="status">{message}</p>}
 {draft&&state&&<><fieldset disabled={busy}>{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea rows={key==='general'||key==='relevance'?5:3} maxLength={2000} value={draft[key as keyof typeof labels]} onChange={event=>{setDraft({...draft,[key]:event.target.value});setResults([])}}/></label>)}
 <h3>Tillägg per källa</h3>{state.sources.map(source=><label key={source.id}>{source.name}<textarea rows={3} maxLength={1000} value={draft.sources[source.id]||''} onChange={event=>{setDraft({...draft,sources:{...draft.sources,[source.id]:event.target.value}});setResults([])}}/></label>)}
 <div className="button-row"><button onClick={()=>void run('save')}>Spara utkast</button><button onClick={()=>void run('activate')}>Aktivera som ny version</button></div>
 <h3>Testa och ompröva</h3><p>Förslag på aktuell sida. Omprövning använder den aktiva versionen och ändrar bara AI-bedömningen.</p>
 {candidates.filter(item=>item.payload.state==='new').map(item=><label className="ai-selection" key={item.entityId}><input type="checkbox" checked={selected.includes(item.entityId)} disabled={!selected.includes(item.entityId)&&selected.length>=3} onChange={event=>setSelected(event.target.checked?[...selected,item.entityId]:selected.filter(id=>id!==item.entityId))}/>{item.payload.title}</label>)}
 <div className="button-row"><button disabled={!selected.length} onClick={()=>void run('test')}>Testa utkast på valda</button><button disabled={!selected.length} onClick={()=>void run('reassess')}>Ompröva med aktiva regler</button></div>
 <details><summary>Versionshistorik</summary>{state.history.map(version=><p key={version.version}>Version {version.version} · {new Date(version.created).toLocaleString('sv-SE')} <button onClick={()=>{setDraft(version.rules);setResults([]);setMessage('Tidigare version inläst som utkast. Aktivera för att börja använda den.')}}>Läs in som utkast</button></p>)}</details></fieldset>
 {results.map(result=><article className="intake-candidate" key={result.id}><h3>{result.title}</h3>{result.skipped?<p>Manuellt beslut bevarat.</p>:<><strong>{decisionLabel(result.decision)}</strong><p>{result.reason}</p><blockquote>{result.evidence}</blockquote><p>{result.summary}</p><details><summary>Bildidé</summary><p>{result.imagePrompt}</p></details></>}</article>)}</>}
 </details>
}
