import { useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { ArrowDownUp, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronDown, Compass, Earth, HandHeart, Heart, Info, Leaf, List, MapPin, MapPinned, PawPrint, Search, ShieldCheck, SlidersHorizontal, Sparkles, Sprout, Sun, Users, Waves, X } from 'lucide-react'
import { categories, checkedAt, searchInitiatives } from '../data/initiatives'
import type { Category, Initiative } from '../data/initiatives'
import InitiativeMap from './InitiativeMap'
import { useWebMCP } from './useWebMCP'

const icons = { natur: Leaf, manniskor: Users, djur: PawPrint, klimat: Sun, hav: Waves, barn: Heart }
function Modal({ title, onClose, children, detail = false }: { title: string; onClose: () => void; children: ReactNode; detail?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null)
  useEffect(() => { const el = ref.current; el?.showModal(); return () => el?.close() }, [])
  return <dialog ref={ref} className={detail ? 'modal detail-modal' : 'modal'} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose() }} aria-labelledby="modal-title"><div className="modal-inner"><div className="modal-heading"><span className="eyebrow">BIDRA</span><button className="icon-button" onClick={onClose} aria-label="Stäng"><X size={21} /></button></div><h2 id="modal-title">{title}</h2>{children}</div></dialog>
}
function InitiativeCard({ item, saved, onSave, onOpen, onHover }: { item: Initiative; saved: boolean; onSave: () => void; onOpen: () => void; onHover: (id: string | null) => void }) {
  const category = categories.find(c => c.id === item.category)!
  const Icon = icons[item.category]
  return <article className="initiative-card" onMouseEnter={() => onHover(item.id)} onMouseLeave={() => onHover(null)} onFocus={() => onHover(item.id)} onBlur={() => onHover(null)}>
    <div className={`card-visual visual-${item.category}`}><button className="card-image-button" onClick={onOpen} aria-label={`Läs om ${item.title}`}>{item.image ? <img src={item.image} alt="" width="600" height="400" loading="lazy" /> : <div className="category-visual"><Icon strokeWidth={1.1} size={62} /><span>{category.label}</span></div>}</button><span className="card-location"><MapPin size={12} />{item.region}</span><button className={`save-button ${saved ? 'is-saved' : ''}`} onClick={onSave} aria-label={`${saved ? 'Ta bort' : 'Spara'} ${item.title}`} aria-pressed={saved}><Bookmark size={17} fill={saved ? 'currentColor' : 'none'} /></button></div>
    <button className="card-copy" onClick={onOpen}><span className="card-organization">{item.organization}<ArrowUpRight size={15} /></span><h3>{item.title}</h3><p>{item.summary}</p></button><div className="card-bottom"><span className={`category-tag tag-${item.category}`}><Icon size={13} />{category.label.split(' & ')[0]}</span><span className="source-note"><Check size={13} /> Källa finns</span></div>
  </article>
}
export default function Bidra() {
  const [initiatives, setInitiatives] = useState<Initiative[]>([])
  const [catalogState, setCatalogState] = useState('loading')
  const [isAdmin, setIsAdmin] = useState(false)
  useEffect(() => { const controller = new AbortController(); fetch('/api/initiatives', { signal: AbortSignal.any([controller.signal, AbortSignal.timeout(15000)]) }).then(async response => { if (!response.ok) throw new Error('catalog'); const data = await response.json(); setInitiatives(data.initiatives); setCatalogState('ready') }).catch(() => { if (!controller.signal.aborted) setCatalogState('error') }); fetch('/api/session', { signal: controller.signal }).then(response => response.json()).then(session => setIsAdmin(session.admin)).catch(() => {}); return () => controller.abort() }, [])
  const [input, setInput] = useState('')
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState<Category | 'all'>('all')
  const [giving, setGiving] = useState('all')
  const [localOnly, setLocalOnly] = useState(false)
  const [sort, setSort] = useState('relevance')
  const [saved, setSaved] = useState<string[]>([])
  const [savedOnly, setSavedOnly] = useState(false)
  const [hovered, setHovered] = useState<string | null>(null)
  const [selected, setSelected] = useState<string | null>(null)
  const [modal, setModal] = useState<'about' | 'how' | 'guide' | 'filters' | null>(null)
  const [mobileMap, setMobileMap] = useState(false)
  const [notice, setNotice] = useState('')
  const [guideChoice, setGuideChoice] = useState<Category | null>(null)
  const [guideStep, setGuideStep] = useState(1)
  const [guideGiving, setGuideGiving] = useState('all')
  const [draftGiving, setDraftGiving] = useState('all')
  const [draftLocal, setDraftLocal] = useState(false)
  const resultsRef = useRef<HTMLDivElement>(null)
  useEffect(() => { try { const value: unknown = JSON.parse(localStorage.getItem('bidra-saved') || '[]'); if (Array.isArray(value)) setSaved(value.filter((id): id is string => typeof id === 'string')) } catch { /* Device storage is optional. */ } }, [])
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 3500); return () => clearTimeout(timer) }, [notice])
  const results = useMemo(() => { let items = searchInitiatives(query, category, giving, localOnly, initiatives); if (savedOnly) items = items.filter(item => saved.includes(item.id)); if (sort === 'name') items = [...items].sort((a, b) => a.organization.localeCompare(b.organization, 'sv')); return items }, [query, category, giving, localOnly, savedOnly, saved, sort, initiatives])
  const activeItem = initiatives.find(item => item.id === selected)
  const reset = () => { setQuery(''); setInput(''); setCategory('all'); setGiving('all'); setLocalOnly(false); setSavedOnly(false) }
  const toggleSave = (id: string) => { const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved(next); try { localStorage.setItem('bidra-saved', JSON.stringify(next)); setNotice(next.includes(id) ? 'Sparat på den här enheten' : 'Borttaget från dina sparade') } catch { setNotice('Sparat för besöket. Webbläsaren tillåter inte lagring.') } }
  const search = (value: string) => { setQuery(value); setInput(value); setSavedOnly(false); resultsRef.current?.scrollTo({ top: 0, behavior: 'smooth' }) }
  const openGuide = () => { setGuideStep(1); setGuideChoice(null); setGuideGiving('all'); setModal('guide') }
  useWebMCP(value => { reset(); setSort('relevance'); setMobileMap(false); setSelected(null); setModal(null); search(value) }, initiatives)
  return <div className="app-shell">
    <a className="skip-link" href="#initiativ">Hoppa till initiativen</a>
    <header className="site-header"><button className="brand" onClick={reset} aria-label="Bidra, visa alla initiativ"><span className="brand-symbol"><img src="/bidra-symbol.svg" alt="" width="46" height="46" /></span>bidra<span className="brand-dot">.</span></button><nav aria-label="Huvudmeny"><button className={!savedOnly ? 'nav-link active' : 'nav-link'} onClick={() => setSavedOnly(false)}>Utforska</button><button className="nav-link" onClick={() => setModal('how')}>Så fungerar Bidra</button><button className="nav-link" onClick={() => setModal('about')}>Om Bidra</button>{isAdmin && <a className="nav-link" href="/admin">Redaktion</a>}</nav><button className={`saved-nav ${savedOnly ? 'active' : ''}`} onClick={() => setSavedOnly(v => !v)} aria-pressed={savedOnly}><Bookmark size={18} /><span>Sparade</span>{saved.length > 0 && <span className="saved-count">{saved.length}</span>}</button></header>
    <main>
      <section className="discovery" aria-labelledby="discovery-title"><div className="discovery-heading"><div><span className="eyebrow"><Sprout size={14} /> FÖR MÄNNISKOR, DJUR OCH NATUR</span><h1 id="discovery-title">Vad vill du <span>bidra till?</span></h1><p>Hitta något du tror på. Upptäck initiativ som gör skillnad.</p></div><button className="guide-button" onClick={openGuide}><Sparkles size={18} /><span>Hjälp mig hitta min hjärtefråga</span><ArrowUpRight size={17} /></button></div><form className="search-form" onSubmit={e => { e.preventDefault(); search(input) }}><Search className="search-leading" size={22} /><label className="sr-only" htmlFor="cause-search">Vad vill du bidra till?</label><input id="cause-search" value={input} onChange={e => setInput(e.target.value)} placeholder="T.ex. bevara skogen eller hjälpa barn som har det svårt" autoComplete="off" />{input && <button type="button" className="clear-search" aria-label="Rensa sökning" onClick={() => search('')}><X size={18} /></button>}<span className="search-country"><MapPin size={17} />Sverige</span><button className="search-submit" type="submit" aria-label="Hitta initiativ">Hitta initiativ <ArrowRight size={18} /></button></form></section>
      <section className="category-bar" aria-label="Filtrera efter hjärtefråga"><div className="category-scroll"><button className={`category-button ${category === 'all' ? 'selected' : ''}`} onClick={() => setCategory('all')} aria-pressed={category === 'all'}><Compass size={19} />Alla initiativ</button>{categories.map(cat => { const Icon = icons[cat.id]; return <button key={cat.id} className={`category-button ${category === cat.id ? 'selected' : ''}`} onClick={() => setCategory(category === cat.id ? 'all' : cat.id)} aria-pressed={category === cat.id}><Icon size={19} />{cat.label}</button> })}</div><button className={`filter-button ${giving !== 'all' || localOnly ? 'filtered' : ''}`} onClick={() => { setDraftGiving(giving); setDraftLocal(localOnly); setModal('filters') }} aria-label="Visa filter"><SlidersHorizontal size={17} /><span>Filter</span>{(giving !== 'all' || localOnly) && <i />}</button></section>
      <section className={`explorer ${mobileMap ? 'show-mobile-map' : ''}`} id="initiativ" aria-label="Utforska initiativ"><div className="results-panel"><div className="results-toolbar"><div><span className="results-eyebrow">{savedOnly ? 'DINA HJÄRTEFRÅGOR' : 'HITTA DIN VÄG ATT GÖRA SKILLNAD'}</span><h2>{savedOnly ? 'Sparade initiativ' : query ? `Resultat för ”${query}”` : category === 'all' ? 'Upptäck initiativ i Sverige' : categories.find(c => c.id === category)!.label}</h2><span className="result-count" aria-live="polite">{catalogState === 'loading' ? 'Hämtar initiativ …' : catalogState === 'error' ? 'Kunde inte hämta initiativen' : `${results.length} initiativ att utforska`}{localOnly ? ' · Lokala insatser' : ''}</span></div><label className="sort-control"><ArrowDownUp size={14} /><span className="sr-only">Sortera initiativ</span><select value={sort} onChange={e => setSort(e.target.value)}><option value="relevance">Relevans</option><option value="name">Organisation A–Ö</option></select><ChevronDown size={12} /></label></div><div className="results-scroll" ref={resultsRef}>{catalogState !== 'ready' ? <div className="empty-state" role="status"><h3>{catalogState === 'loading' ? 'Hämtar initiativen …' : 'Initiativen kunde inte hämtas'}</h3>{catalogState === 'error' && <><p>Försök igen om en stund.</p><button className="primary-button" onClick={() => window.location.reload()}>Försök igen</button></>}</div> : results.length ? <div className="cards-grid">{results.map(item => <InitiativeCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={() => toggleSave(item.id)} onOpen={() => setSelected(item.id)} onHover={setHovered} />)}</div> : <div className="empty-state"><Search size={32} /><h3>{savedOnly ? 'Dina hjärtefrågor får plats här' : 'Vi hittade inget som matchar ännu'}</h3><p>{savedOnly ? 'Spara ett initiativ med bokmärket så hittar du tillbaka. Sparade initiativ stannar på den här enheten.' : 'Bidra börjar med ett litet urval. Prova skog, djur, barn eller en annan filtrering.'}</p><button className="primary-button" onClick={reset}>Utforska alla initiativ <ArrowRight size={17} /></button></div>}<div className="curation-note"><Sprout size={16} /><p>Ett första, handplockat urval. Fler vägar att bidra får växa fram.</p></div></div></div><InitiativeMap items={results} selected={selected} hovered={hovered} onSelect={setSelected} /></section>
    </main>
    <footer className="site-footer"><span><ShieldCheck size={16} />Du bidrar direkt hos organisationen</span><span className="footer-center">En liten handling kan bli början på något större.</span><button onClick={() => setModal('how')}>Om urvalet och våra källor <ArrowUpRight size={14} /></button></footer>
    <button className="mobile-view-toggle" onClick={() => setMobileMap(v => !v)}>{mobileMap ? <List size={18} /> : <MapPinned size={18} />}{mobileMap ? 'Visa lista' : 'Visa karta'}</button>
    {notice && <div className="toast" role="status"><Check size={16} />{notice}</div>}
    {activeItem && <Modal title={activeItem.title} onClose={() => setSelected(null)} detail><div className="detail-organization"><span>{activeItem.organization}</span><button className="icon-button" aria-label="Spara initiativ" aria-pressed={saved.includes(activeItem.id)} onClick={() => toggleSave(activeItem.id)}><Bookmark size={20} fill={saved.includes(activeItem.id) ? 'currentColor' : 'none'} /></button></div>{activeItem.image && <figure className="detail-image"><img src={activeItem.image} alt="Illustrativ bild för initiativets hjärtefråga" /><figcaption>Genrebild · visar inte den specifika verksamheten</figcaption></figure>}<p className="detail-summary">{activeItem.summary}</p><div className="detail-location"><MapPin size={20} /><div><strong>{activeItem.region}</strong><p>{activeItem.geography}</p></div></div><h3>Så kan du bidra</h3><p>{activeItem.contribution}</p><div className="trust-box"><ShieldCheck size={22} /><div><strong>Öppen information, egna beslut</strong><p>Sammanfattat från organisationens egen webbplats. Källan läst {activeItem.sourceReadAt ? new Date(activeItem.sourceReadAt + 'T12:00:00').toLocaleDateString('sv-SE', { year: 'numeric', month: 'long', day: 'numeric' }) : checkedAt}. Bidra har inte gjort någon oberoende granskning av verksamheten eller effekten.</p><a href={activeItem.source} target="_blank" rel="noopener noreferrer">Läs originalkällan <ArrowUpRight size={14} /></a></div></div><h3>Vad händer med mitt bidrag?</h3><p>Bidra följer ännu inte upp enskilda gåvor. Organisationen kan berätta om sitt arbete och sin resultatredovisning.</p><a className="primary-button donate-link" href={activeItem.donate} target="_blank" rel="noopener noreferrer">{activeItem.giving.includes('pengar') ? 'Bidra hos organisationen' : 'Engagera dig hos organisationen'}<ArrowUpRight size={18} /></a><p className="donation-note">Du går vidare till {activeItem.organization}. Bidra hanterar inga pengar.</p></Modal>}
    {modal === 'how' && <Modal title="Från hjärtefråga till handling." onClose={() => setModal(null)}><div className="how-step"><span>01</span><div><h3>Börja med det du bryr dig om</h3><p>Sök efter en fråga, en organisation eller en ort. Du kan också välja en kategori eller låta guiden hjälpa dig.</p></div></div><div className="how-step"><span>02</span><div><h3>Utforska med öppna ögon</h3><p>Se vad initiativet arbetar med, var arbetet hör hemma och hur du kan bidra. Varje post länkar till organisationens egen källa.</p></div></div><div className="how-step"><span>03</span><div><h3>Ta nästa steg direkt</h3><p>Du ger din gåva eller anmäler ditt intresse hos organisationen. Bidra tar inte emot pengar.</p></div></div><div className="trust-box"><Info size={21} /><div><strong>Om den första versionen</strong><p>Urvalet är litet och manuellt sammanställt. Sökningen använder ord och kategorier. Datum för källäsning visas på respektive initiativ; uppgifter kan ändras. ”Källa finns” betyder att originalinformation finns att läsa, inte att Bidra garanterar kvalitet eller effekt.</p></div></div></Modal>}
    {modal === 'about' && <Modal title="Mer omtanke. Fler möjligheter." onClose={() => setModal(null)}><div className="about-symbol"><img src="/bidra-symbol.svg" alt="" width="64" height="64" /></div><p className="detail-summary">Bidra börjar i en enkel tanke: människor, djur och natur är värda vår omsorg.</p><p>Det ska vara lättare att hitta ett konkret sätt att bidra till det man tror på. Här får stora och små initiativ ta plats, med tydlig information som hjälper dig att välja själv.</p><p>Vi börjar i Sverige. Det här är en första prototyp, med ett handplockat urval och utrymme att växa tillsammans.</p><h3>Bilder</h3><p className="photo-credits">Illustrativa fotografier via Unsplash: <a href="https://unsplash.com/photos/Ll1fQP_clj4" target="_blank" rel="noopener noreferrer">Paul Lichtblau</a> (skog), <a href="https://unsplash.com/photos/kgZfQW3QUNk" target="_blank" rel="noopener noreferrer">Oleh Holodyshyn</a> (kust), <a href="https://unsplash.com/photos/W3SEyZODn8U" target="_blank" rel="noopener noreferrer">Priscilla Du Preez</a> (gemenskap). Bilderna föreställer inte de listade organisationernas verksamhet.</p></Modal>}
    {modal === 'filters' && <Modal title="Hitta ett sätt som passar dig" onClose={() => setModal(null)}><fieldset><legend>Hur vill du bidra?</legend>{[{ value: 'all', label: 'Visa alla sätt' }, { value: 'pengar', label: 'Ge en gåva' }, { value: 'tid', label: 'Bidra med min tid' }].map(option => <label className="radio-option" key={option.value}><input type="radio" name="giving" checked={draftGiving === option.value} onChange={() => setDraftGiving(option.value)} />{option.label}</label>)}</fieldset><label className="check-option"><input type="checkbox" checked={draftLocal} onChange={e => setDraftLocal(e.target.checked)} /><div>Visa bara lokala insatser<span>Initiativ med ett område på kartan</span></div></label><button className="primary-button wide" onClick={() => { setGiving(draftGiving); setLocalOnly(draftLocal); setModal(null) }}>Visa initiativ <ArrowRight size={18} /></button></Modal>}
    {modal === 'guide' && <Modal title={guideStep === 1 ? 'Vad ligger dig varmt om hjärtat?' : 'Hur vill du göra skillnad?'} onClose={() => setModal(null)}><p className="guide-progress">STEG {guideStep} AV 2 <span className={guideStep === 2 ? 'complete' : ''} /></p>{guideStep === 1 ? <><p>Välj något som känns viktigt just nu. Du kan alltid utforska fler frågor sedan.</p><div className="guide-grid">{categories.map(c => { const Icon = icons[c.id]; return <button key={c.id} className={guideChoice === c.id ? 'chosen' : ''} aria-pressed={guideChoice === c.id} onClick={() => setGuideChoice(c.id)}><Icon size={25} /><span>{c.label}</span>{guideChoice === c.id && <Check size={15} />}</button> })}</div><button disabled={!guideChoice} className="primary-button wide" onClick={() => setGuideStep(2)}>Nästa <ArrowRight size={18} /></button></> : <><div className="guide-giving">{[{ value: 'pengar', label: 'Ge en gåva', icon: Heart }, { value: 'tid', label: 'Bidra med min tid', icon: HandHeart }, { value: 'all', label: 'Jag är öppen för båda', icon: Earth }].map(({ value, label, icon: Icon }) => <button className={guideGiving === value ? 'chosen' : ''} key={value} onClick={() => setGuideGiving(value)} aria-pressed={guideGiving === value}><Icon size={22} />{label}{guideGiving === value && <Check size={18} />}</button>)}</div><div className="guide-actions"><button className="text-button" onClick={() => setGuideStep(1)}>Tillbaka</button><button className="primary-button" onClick={() => { reset(); setCategory(guideChoice || 'all'); setGiving(guideGiving); setModal(null) }}>Visa mina initiativ <ArrowRight size={18} /></button></div></>}</Modal>}
  </div>
}
