import {useEffect,useState} from 'react'
import {vibeClient} from '../lib/vibe'
type Item={id:string;revision:number;status:string;manual:number;error?:string;checked_at:string;data:{title:string;url:string;excerpt:string};assessment?:{reason:string;evidence:string;proposal?:{summary:string;giving:string[];region:string}}}
type State={running?:boolean;counts:Record<string,number>;sources:{id:string;name:string;url:string;enabled:number;last_run?:string;next_run?:string;error?:string;discovered:number}[];items:Item[];runs:{id:number;started:string;finished?:string;details?:string}[]}
const labels:Record<string,string>={pending:'Väntar på AI',processing:'Bearbetas',retry:'Försöker igen',published:'Publicerad',review:'Behöver granskas',rejected:'Bortsorterad av AI',hidden:'Manuellt borttagen',duplicate:'Finns redan',error:'Fel',expired:'Avslutad'}
const date=(s?:string)=>s?new Date(s).toLocaleString('sv-SE'):'Inte körd än'
async function request(body?:unknown){const c=await vibeClient();const r=await c.authorizedFetch(new URL('/api/editor/collection',location.origin),await c.connect('app:content'),{...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(60000)});const result=await r.json();if(!r.ok)throw new Error(result.error);return result as State}
export default function Collection({initialFilter='all'}:{initialFilter?:string}){
 const [state,setState]=useState<State>(),[filter,setFilter]=useState(initialFilter),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{let alive=true;const load=()=>void request().then(s=>{if(alive)setState(s)}).catch(e=>{if(alive)setMessage(e.message)});load();const t=setInterval(load,30000);return()=>{alive=false;clearInterval(t)}},[])
 async function action(action:string,item?:Item,source?:State['sources'][number]){setBusy(true);setMessage('');try{setState(await request({action,id:item?.id||source?.id,revision:item?.revision,...(source?{enabled:!source.enabled}:{})}))}catch(e){setMessage(e instanceof Error?e.message:'Åtgärden misslyckades')}finally{setBusy(false)}}
 return <section className="collection-dashboard"><p className="results-eyebrow">REDAKTION</p><h1>Automatisk insamling</h1><p>Källorna kontrolleras var sjätte timme. Kön bearbetas varje timme. Tydliga möjligheter publiceras automatiskt; osäkra förslag väntar här. Manuella beslut respekteras.</p>
 {message&&<p role="alert">{message}</p>}{state?.running&&<p role="status">Insamling och bearbetning pågår… Listan uppdateras automatiskt.</p>}
 <div className="collection-sources">{state?.sources.map(s=><article key={s.id}><strong>{s.name}</strong><span>{s.enabled?'Aktiv':'Pausad'} · {s.discovered} länkar i senaste katalogen</span><small>Senast: {date(s.last_run)}<br/>Nästa kontroll: {s.enabled?date(s.next_run):'Pausad'}</small>{s.error&&<p role="alert">{s.error}</p>}<div><a href={s.url} target="_blank" rel="noreferrer">Källa ↗</a><button disabled={busy} onClick={()=>void action('source',undefined,s)}>{s.enabled?'Pausa':'Aktivera'}</button></div></article>)}</div>
 <label>Visa <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Alla förslag ({state?.items.length||0})</option>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v} ({state?.counts[k]||0})</option>)}</select></label>
 <div className="collection-items">{state?.items.filter(x=>filter==='all'||x.status===filter).map(item=><article key={item.id}><div><small>{labels[item.status]||item.status}{item.manual?' · Manuellt beslut':''}</small><h2>{item.data.title}</h2><p>{item.assessment?.proposal?.summary||item.data.excerpt.slice(0,250)}</p><p><strong>{item.assessment?.reason}</strong></p>{item.error&&<p role="alert">{item.error}</p>}<details><summary>Källstöd och kontroll</summary><p>{item.assessment?.evidence}</p><p>{item.data.excerpt}</p><small>Kontrollerad {date(item.checked_at)} · {item.assessment?.proposal?.region}</small></details></div><div className="collection-actions"><a href={item.data.url} target="_blank" rel="noreferrer">Öppna källan ↗</a>{item.status!=='published'&&item.assessment?.proposal?.giving.length? <button disabled={busy||state.running} onClick={()=>void action('publish',item)}>Publicera</button>:null}{!['hidden','duplicate'].includes(item.status)&&<button disabled={busy||state.running} onClick={()=>void action('hide',item)}>{item.status==='published'?'Ta bort från sajten':'Sortera bort'}</button>}{['hidden','rejected','expired'].includes(item.status)&&<button disabled={busy||state.running} onClick={()=>void action('restore',item)}>Återställ till granskning</button>}{['error','review','rejected'].includes(item.status)&&<button disabled={busy||state.running} onClick={()=>void action('retry',item)}>Bedöm med aktuella regler</button>}</div></article>)}</div>
 {state?.items.length===0&&<p>Inga förslag insamlade ännu. Källornas driftstatus visas ovan.</p>}
 <details><summary>Senaste körningar</summary>{state?.runs.map(run=><p key={run.id}>{date(run.started)} · {run.finished?'Klar':'Avbruten eller pågår'}{run.details&&(()=>{const d=JSON.parse(run.details);return ` · ${d.fetched} hämtade · ${d.published} publicerade · ${d.review} för granskning · ${d.rejected} bortsorterade · ${d.errors} fel`})()}</p>)}</details>
 </section>
}
