import { useEffect, useState } from 'react'
import { categories } from '../data/initiatives'
import type { Initiative } from '../data/initiatives'

type Entry = { id: string; draft: Initiative; status: string; revision: number; isPublic: boolean }
type Event = { revision: number; action: string; note: string; created_at: string }
const statuses: Record<string, string> = { draft: 'Utkast', pending: 'För granskning', published: 'Publicerad', archived: 'Arkiverad' }
const actions: Record<string, string> = { create: 'Skapad', save: 'Utkast sparat', submit: 'Skickad till granskning', approve: 'Godkänd och publicerad', return: 'Åter till utkast', archive: 'Arkiverad' }
const blank = (): Initiative => ({ id: '', title: '', organization: '', category: 'natur', region: '', scope: 'national', geography: '', summary: '', contribution: '', source: '', donate: '', keywords: [], giving: ['pengar'] })
async function api(path: string, body?: unknown) {
  const response = await fetch(path, { signal: AbortSignal.timeout(15000), ...(body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) })
  const data = await response.json()
  if (!response.ok) throw new Error(data.error || 'Något gick fel.')
  return data
}
export default function RegistryAdmin() {
  const [access, setAccess] = useState<'loading' | 'admin' | 'denied'>('loading')
  const [entries, setEntries] = useState<Entry[]>([])
  const [selected, setSelected] = useState<Entry | null>(null)
  const [draft, setDraft] = useState<Initiative | null>(null)
  const [filter, setFilter] = useState('all')
  const [note, setNote] = useState('')
  const [sourceReadAt, setSourceReadAt] = useState('')
  const [checks, setChecks] = useState<Record<string, boolean>>({})
  const [history, setHistory] = useState<Event[]>([])
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [dirty, setDirty] = useState(false)
  const refresh = async () => { const data = await api('/api/admin/entries'); setEntries(data.entries); return data.entries as Entry[] }
  useEffect(() => { let alive = true; api('/api/session').then(async session => { if (!alive) return; setAccess(session.admin ? 'admin' : 'denied'); if (session.admin) await refresh() }).catch(e => { if (alive) setError(e.message) }); return () => { alive = false } }, [])
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault() }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [dirty])
  useEffect(() => { let alive = true; setHistory([]); if (selected) api(`/api/admin/entries/${selected.id}`).then(data => { if (alive) setHistory(data.history) }).catch(e => { if (alive) setError(e.message) }); return () => { alive = false } }, [selected])
  const choose = (entry: Entry | null) => {
    if (dirty && !window.confirm('Lämna ändringarna utan att spara?')) return
    setSelected(entry); setDraft(entry ? structuredClone(entry.draft) : blank()); setDirty(false); setNote(''); setChecks({}); setSourceReadAt(''); setError(''); setMessage('')
  }
  const field = <K extends keyof Initiative>(key: K, value: Initiative[K]) => { setDraft(current => current ? { ...current, [key]: value } : current); setDirty(true) }
  const act = async (action: string) => {
    if (!draft) return
    setBusy(true); setError(''); setMessage('')
    try {
      const result = await api(`/api/admin/entries${selected ? `/${selected.id}` : ''}`, { action, revision: selected?.revision, draft, note, sourceReadAt, checks })
      const updated = await refresh(); const next = updated.find(entry => entry.id === (selected?.id || result.id))!
      setSelected(next); setDraft(structuredClone(next.draft)); setDirty(false); setChecks({}); setNote(''); setSourceReadAt(''); setMessage(actions[selected ? action : 'create'] || 'Sparat')
    } catch (e) { setError(e instanceof Error ? e.message : 'Åtgärden misslyckades.') }
    finally { setBusy(false) }
  }
  return <main className="editor-page"><header className="editor-header"><a href="/" className="editor-brand">bidra.</a><span>Redaktion</span><a href="/">Till initiativen ↗</a></header><div className="editor-intro"><span className="eyebrow">ETT OMSORGSFULLT URVAL</span><h1>Ge initiativen plats.</h1><p>Spara ett utkast, kontrollera källorna och publicera när uppgifterna är redo.</p></div>
    {error && <div className="editor-error" role="alert">{error}<button onClick={() => window.location.reload()}>Läs in senaste versionen</button></div>}
    {access === 'loading' && !error && <p role="status">Kontrollerar behörighet …</p>}
    {access === 'denied' && <p>Redaktionen är tillgänglig för sajtens redaktör. <a href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top">Logga in med rätt konto</a>.</p>}
    {access === 'admin' && <div className="editor-layout"><aside className="editor-sidebar"><button className="primary-button" disabled={busy} onClick={() => choose(null)}>+ Nytt initiativ</button><label>Visa<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Alla initiativ ({entries.length})</option>{Object.entries(statuses).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><div className="editor-entries">{entries.filter(entry => filter === 'all' || entry.status === filter).map(entry => <button disabled={busy} key={entry.id} className={selected?.id === entry.id ? 'selected' : ''} onClick={() => choose(entry)}><strong>{entry.draft.title}</strong><span>{entry.draft.organization}</span><small>{statuses[entry.status]}{entry.isPublic && entry.status !== 'published' ? ' · tidigare version synlig' : ''}</small></button>)}</div></aside>
    <section className="editor-workspace">{!draft ? <div className="editor-welcome"><h2>Ett initiativ i taget.</h2><p>Välj en post till vänster eller börja med ett nytt initiativ. De åtta ursprungliga posterna är importerade; de har ännu ingen redaktionell granskningshistorik.</p></div> : <><div className="editor-title"><h2>{selected ? draft.organization : 'Nytt initiativ'}</h2><span>{selected ? `${statuses[selected.status]} · version ${selected.revision}` : 'Ej sparat'}</span></div><p>{selected?.isPublic ? 'Besökaren ser den senast publicerade versionen tills du godkänner ett nytt utkast.' : 'Det här initiativet visas inte för besökare.'}</p>
    <form onSubmit={e => { e.preventDefault(); void act('save') }}><fieldset disabled={busy}><div className="editor-fields">{(['title', 'organization', 'region'] as const).map((key, index) => <label key={key}>{['Rubrik', 'Organisation', 'Ort eller område'][index]}<input required maxLength={160} value={draft[key]} onChange={e => field(key, e.target.value)} /></label>)}<label>Hjärtefråga<select value={draft.category} onChange={e => field('category', e.target.value as Initiative['category'])}>{categories.map(cat => <option key={cat.id} value={cat.id}>{cat.label}</option>)}</select></label><label>Geografisk räckvidd<select value={draft.scope} onChange={e => field('scope', e.target.value as Initiative['scope'])}><option value="national">Hela Sverige · utan kartmarkör</option><option value="local">Lokalt område · med kartmarkör</option></select></label><label>Bild<select value={draft.image || ''} onChange={e => field('image', e.target.value || undefined)}><option value="">Kategoriillustration</option><option value="/images/forest.jpg">Skog</option><option value="/images/community.jpg">Gemenskap</option><option value="/images/coast.jpg">Kust</option></select></label>{draft.scope === 'local' && <>{[0, 1].map((index) => <label key={index}>{index === 0 ? 'Longitud (öst/väst)' : 'Latitud (norr/söder)'}<input type="number" step="any" required min={index === 0 ? -180 : -85} max={index === 0 ? 180 : 85} value={draft.coordinates?.[index] ?? ''} onChange={e => { const next: [number, number] = [...(draft.coordinates || [0, 0])]; next[index] = e.target.valueAsNumber; field('coordinates', next) }} /></label>)}</>}{(['geography', 'summary', 'contribution'] as const).map((key, index) => <label className="full-field" key={key}>{['Vad representerar platsen eller området?', 'Kort sammanfattning', 'Så kan man bidra'][index]}<textarea required maxLength={key === 'summary' ? 600 : 2000} rows={3} value={draft[key]} onChange={e => field(key, e.target.value)} /></label>)}{(['source', 'donate'] as const).map((key, index) => <label key={key}>{index === 0 ? 'Originalkälla (https)' : 'Länk för att bidra (https)'}<input required type="url" value={draft[key]} onChange={e => field(key, e.target.value)} /></label>)}<label className="full-field">Sökord, separerade med kommatecken<input value={draft.keywords.join(',')} onChange={e => field('keywords', e.target.value.split(','))} /></label><div className="editor-checks">{(['pengar', 'tid'] as const).map(mode => <label key={mode}><input type="checkbox" checked={draft.giving.includes(mode)} onChange={e => field('giving', e.target.checked ? [...draft.giving, mode] : draft.giving.filter(x => x !== mode))} />{mode === 'pengar' ? 'Ge pengar' : 'Bidra med tid'}</label>)}</div></div><button className="primary-button" type="submit">{busy ? 'Sparar …' : 'Spara utkast'}</button>{dirty && <span className="editor-unsaved">Du har osparade ändringar.</span>}</fieldset></form>
    {selected && <section className="editor-review"><h3>Granska och publicera</h3><p>Spara ändringarna först. Kontrollera uppgifterna hos organisationen innan du godkänner dem. Detta är en källkontroll, ingen oberoende granskning av verksamhetens effekt.</p><div className="editor-source-links"><a href={selected.draft.source} target="_blank" rel="noopener noreferrer">Öppna sparad originalkälla ↗</a><a href={selected.draft.donate} target="_blank" rel="noopener noreferrer">Öppna sparad bidragslänk ↗</a></div><fieldset disabled={busy || dirty}>{selected.status === 'draft' && <button className="primary-button" onClick={() => act('submit')}>Skicka till granskning</button>}{selected.status === 'pending' && <><label>Källan läst<input type="date" max={new Date().toISOString().slice(0,10)} value={sourceReadAt} onChange={e => setSourceReadAt(e.target.value)} /></label><div className="editor-checks vertical">{Object.entries({ identity: 'Organisationen och initiativet stämmer med källan', source: 'Sammanfattningen och sättet att bidra stöds av källan', geography: 'Området och eventuell kartmarkör är korrekt beskrivna', donation: 'Bidragslänken går till rätt organisation och fungerar' }).map(([key, label]) => <label key={key}><input type="checkbox" checked={Boolean(checks[key])} onChange={e => setChecks({ ...checks, [key]: e.target.checked })} />{label}</label>)}</div></>}<label>Granskningsanteckning eller skäl för åtgärden<textarea rows={3} maxLength={2000} value={note} onChange={e => setNote(e.target.value)} placeholder="Vad kontrollerades, eller vad behöver ändras?" /></label><div className="editor-actions">{selected.status === 'pending' && <><button className="primary-button" disabled={!sourceReadAt || Object.values(checks).filter(Boolean).length !== 4 || note.trim().length < 15} onClick={() => act('approve')}>Godkänn och publicera</button><button className="secondary-button" disabled={note.trim().length < 5} onClick={() => act('return')}>Tillbaka till utkast</button></>}{selected.status !== 'archived' && <button className="secondary-button" disabled={note.trim().length < 5} onClick={() => { if (window.confirm('Arkivera initiativet? Det tas bort från besökarens lista och karta. Historiken sparas.')) void act('archive') }}>Arkivera</button>}</div></fieldset>{selected.status === 'archived' && <p>Spara som utkast för att börja återpublicera initiativet.</p>}</section>}
    {message && <p className="editor-success" role="status">{message}</p>}{selected && <section className="editor-history"><h3>Historik</h3>{history.length ? <ol>{history.map(event => <li key={event.revision}><strong>{actions[event.action] || event.action}</strong><span>Version {event.revision} · {new Date(event.created_at).toLocaleString('sv-SE')}</span>{event.note && <p>{event.note}</p>}</li>)}</ol> : <p>Importerad från det ursprungliga urvalet. Ingen ny granskning registrerad ännu.</p>}</section>}</>}</section></div>}
  </main>
}
