/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CloudContentRouteImport } from './routes/cloud-content'
import { Route as VibeCallbackRouteImport } from './routes/vibe-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudContentRoute = CloudContentRouteImport.update({
  id: '/cloud-content',
  path: '/cloud-content',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCallbackRoute = VibeCallbackRouteImport.update({
  id: '/vibe-callback',
  path: '/vibe-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-content': typeof CloudContentRoute
  '/vibe-callback': typeof VibeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-content': typeof CloudContentRoute
  '/vibe-callback': typeof VibeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-content': typeof CloudContentRoute
  '/vibe-callback': typeof VibeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/cloud-content' | '/vibe-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/cloud-content' | '/vibe-callback'
  id: '__root__' | '/' | '/admin' | '/cloud-content' | '/vibe-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CloudContentRoute: typeof CloudContentRoute
  VibeCallbackRoute: typeof VibeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-content': {
      id: '/cloud-content'
      path: '/cloud-content'
      fullPath: '/cloud-content'
      preLoaderRoute: typeof CloudContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-callback': {
      id: '/vibe-callback'
      path: '/vibe-callback'
      fullPath: '/vibe-callback'
      preLoaderRoute: typeof VibeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CloudContentRoute: CloudContentRoute,
  VibeCallbackRoute: VibeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
